### ISSUE TITLE
Control -Werror through build options (CFLAGS) not by hardcoding in Makefile.am

### ISSUE THREAD

**Issue by joachimmetz** [sleuthkit/sleuthkit#3012] opened 2024-10-05 05:17 UTC
Currently Makefile.am contains hardcoded -Werror flags

https://github.com/sleuthkit/sleuthkit/blob/develop/Makefile.am#L291

Can this be changed to be controlled via CFLAGS ?

**Comment by uckelman** [comment] 2024-10-05 11:05
What's the rationale for doing this?

**Comment by joachimmetz** [comment] 2024-10-05 11:22
different compilers behave differently with the -Werror flag, this causes builds to unnecessary fail

**Comment by simsong** [comment] 2024-10-05 12:10
In the bulk_extractor configure macros, I manually check for each flag.

Are you suggesting that we set CFLAGS=-Werror and CPPFLAGS=-Werror in our GitHub CI scripts, rather than having it hardcoded in Makefile.am?

**Comment by uckelman** [comment] 2024-10-05 12:31
> different compilers behave differently with the -Werror flag

Would you give an example?

**Comment by joachimmetz** [comment] 2024-10-05 14:30
> Are you suggesting that we set CFLAGS=-Werror and CPPFLAGS=-Werror in our GitHub CI scripts, rather than having it hardcoded in Makefile.am?

So I don't know what the intent of only having `-Werror` on 2 sub-directories? If you want to use it as a smoke test, indeed it might be better to set in the test configuration.

> Would you give an example?

An example of what specifically? https://embeddedartistry.com/blog/2017/05/22/werror-is-not-your-friend/ might provide you with the necessary context

**Comment by uckelman** [comment] 2024-10-05 14:36
> So I don't know what the intent of only having `-Werror` on 2 sub-directories? If you want to use it as a smoke test, indeed it might be better to set in the test configuration.

I believe the intent is that the code in those subdirectories is in a state where there are no warnings, so it can be compiled with `-Werror`, whereas code elsewhere cannot be yet. It's a way of incrementally getting to the point where `-Werror` can be used universally.

> An example of what specifically? 

I was hoping for an example of what you said: "different compilers behave differently with the -Werror flag".

**Comment by joachimmetz** [comment] 2024-10-05 15:20
> I was hoping for an example of what you said: "different compilers behave differently with the -Werror flag".

This is mentioned in the article I link ed

```
Different vendors have different warning sets and warning detection logic, even if they support a common array of warning settings (such as with GCC and Clang). Code that compiles with one toolchain warning-free may not do so with another toolchain. We often see this with our open-source projects. We primarily use Clang, and it is a common occurrence that our [CI](https://embeddedartistry.com/fieldmanual-terms/continuous-integration/) server will report a warning when compiling our “warning-free” code with GCC.
```

**Comment by uckelman** [comment] 2024-10-05 16:05
I don't see any example there, only a claim that it happens.

**Comment by joachimmetz** [comment] 2024-10-05 16:09
> I don't see any example in what you quoted, only a claim that it happens.

sigh

**Comment by uckelman** [comment] 2024-10-05 16:10
My recommendation is that we move to setting `-Werror` for CI builds after we've eliminated all the warnings which appear in CI builds. The uses of `-Werror` presently prevent more warnings from appearing in the code they cover. So long as the problem is hypothetical, they shouldn't be removed before we have an alternative.

**Comment by simsong** [comment] 2024-10-05 16:11
> My recommendation is that we move to setting `-Werror` for CI builds after we've eliminated all the warnings which appear in CI builds. The uses of `-Werror` presently prevent more warnings from appearing in the code they cover. So long as the problem is hypothetical, they shouldn't be removed before we have an alternative.

If we move it to the CI system now, we won't have any problems in the CI, it will just be fewer errors for people running locally, right?

**Comment by uckelman** [comment] 2024-10-05 16:12
No, because the current uses of `-Werror` cover only particular subdirectories, while setting `-Werror` in `CFLAGS` and `CXXFLAGS` would cover all the code.

**Comment by uckelman** [comment] 2024-10-05 16:13
We're not dramatically far off being able to move `-Werror` out to the global user variables, but we can't do it and have passing builds right now.

**Comment by uckelman** [comment] 2024-10-24 23:21
@simsong Closed by #3050.

**Closed** 2024-10-25 02:34 UTC

**Comment by joachimmetz** [comment] 2024-10-25 04:47
Flags are still in Makefile. am https://github.com/sleuthkit/sleuthkit/blob/develop/Makefile.am#L4

```
AM_CPPFLAGS = -I$(srcdir)/tsk
AM_CFLAGS = -Wall -Wextra -Wno-unused-parameter
AM_CXXFLAGS = -Wall -Wextra -Wno-unused-parameter -Wno-overloaded-virtual
```

**Comment by simsong** [comment] 2024-10-25 06:22
Well that's better...

**Comment by uckelman-sf** [comment] 2024-10-25 09:43
This issue was about `-Werror`, which is no longer there.

`-Wall` and `-Wextra` are appropriate. The other two, maybe open an issue for them?
